### ISSUE TITLE
XLS import problem

### ISSUE THREAD

**Issue by dtrdewaele** [iRail/The-DataTank#102]
When I import an XLS file into The Datatank, I got this error.
Undefined index: gen_resource_id on line 85 in file /Volumes/Data/git/The-DataTank/model/resources/GenericResource.class.php.

I make use of the range parameters.

**Comment by coreation** [comment]
Hi Dieter,

This could be a few things, could you send me the XLS file ? ( or a similar file with sensitive data left out ) Also, are you working with the latest development branch -code ? The bug is a good thing, because we've opened up already a lot of XLS files without many problems, so this means we still have looked something over!

**Comment by dtrdewaele** [comment]
Hi Jan,

For this project, I work with the production branch. At Digipolis we want
to have stable software, so that's the reason why :)

In attachment you have the XLS file.

Regards

Dieter

2012/7/2 Jan Vansteenlandt <
reply@reply.github.com

**Comment by coreation** [comment]
Ah, I think we've found your problem then. I assume you link the 'production' branch with the 'master' branch. This is however not true. We've been fixing quite a few bugs and features on the develop branch, and left the master branch for what is was. The fixing and implementing has been finished for over a month now. This is ofcourse a miscommunication from our side. If you pull the code from the develop branch it should lead to working code, this code has been tested by using it to upload all of the data which is on data.gent.be at the moment with no current bugs reported to the day. 

P.S. Can you email me the attachment, on the comment it said that you added it, but afaik you can't add any attachment to comments ? If you email it to Lieven, it'll get to me as well, he's right beside me shouldersurfing ;)

**Comment by dtrdewaele** [comment]
Ok, I'll checkout develop branch than! I'll let you know :)

Thx in advance

2012/7/2 Jan Vansteenlandt <
reply@reply.github.com

**Comment by dtrdewaele** [comment]
I've done this, but the problem stays the same ...

2012/7/2 Dieter De Waele dtrdewaele@gmail.com

**Comment by coreation** [comment]
You're most welcome ! We had a good documentation wiki, but it got hacked and now it's just full of stuff you find in spam... Pieter is working on it.

**Comment by coreation** [comment]
Hm, can you email me ( or Lieven ) the XLS file and the parameters you send along with it ?
