### ISSUE TITLE
Any known issues with PHP versions or any special modules needed?

### ISSUE THREAD

**Issue by dtrdewaele** [iRail/The-DataTank#115]
DataTank installed at MAMP on PHP 5.3.6 and works perfect.
Same branch (develop) installed on PHP 5.3.8 and CSV import does not work...

Are there any special requirements next to PHP 5.3.X?

Regards

Dieter

**Comment by coreation** [comment]
Hmm, not that I know of, I'll check and see what version I have and get back to you asap.

**Comment by dtrdewaele** [comment]
I fixed a PHP error, so I now get error info from TDT.

Ik keep getting This package name ( packagename here ) has not been created yet.

On localhost, everything goes ok :)

**Comment by coreation** [comment]
So if I understand it correctly you have 2 TDT instances, one localhost one on some server ? On localhost everything goes well, on the remote one not ? You could check in the database back-end if the package and/or resource has been created.

**Comment by coreation** [comment]
Hmm, by looking at the changelog of php they did change something to fgetcsv() , but it's a bug fix rather than a functionality change.

**Comment by coreation** [comment]
Hej dieter,

I just did an installation on my desktop of the datatank, with a brand new wampserver containing php 5.3.8 and a csv import works fine... Any updates on the error from your side ?

**Comment by dtrdewaele** [comment]
Hi,
I wasn't at the office yesterday and could not access the PhpMyAdmin :)
The resource isn't created in the DB... Very strange...

**Comment by dtrdewaele** [comment]
Hmm not fully sure of this, but I get the impression that the issue isn't an issue on TDT but on our Firewall configuration. A PUT command seems like being transformed into a GET command. POST works...
I'll try sysadmins and get back on this.

**Comment by coreation** [comment]
Okay! The more "know issues" we have, even if it's with non-TDT software, but supporting software, the more we can help other ppl with identifying future problems.

**Comment by dtrdewaele** [comment]
Found the solution.
Our server is hosting DirectAdmin and apparently this system hasn't got a allow,deny settings in the vhosts config of Apache.

After adding 
Order allow,deny
Allow from all

to the vhost of the website, the system works...

Not a DataTank issue, but a nice to know :)

Dieter

**Comment by coreation** [comment]
Okay thanks ! May help some people in the future ;)
