### ISSUE TITLE
Possibility to add example URI to documentation

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/The-DataTank#117]
In TDTInfo, I also want to be able to specify an example URI. For instance, for iRail's NMBS/Departures, the call is a little complicated. Adding an example URI like http://data.irail.be/NMBS/Departures/Gent Sint Pieters/2012/07/25/12/00 would come in very handy.

**Comment by coreation** [comment]
If this piece of documentation is optional (which I think it may be) then this will not be a major change, but rather easy to implement ;).

**Comment by pietercolpaert** [comment]
Exactly. So do it ;)

**Comment by coreation** [comment]
Done! But it's as part of the detailed information, so in TDTInfo/Resources you'll still only see documentation, parameters, requiredparameters. On TDTAdmin/Resources however you'll see the full definition with the example_uri, if given ofcourse. I have a small tingely feeling you want to have the example uri passed with TDTInfo/Resources as well ?

**Comment by pietercolpaert** [comment]
Good thinking ;)

By the way, now that we are adding installed resources through PUT requests, wouldn't it be nice to delete the getDocumentation from AReader and instead putting that in the documentation when doing a PUT?

An installed resource developer can then provide an installer script together with his installed resource code which will put the installed resource in the right location.

**Comment by coreation** [comment]
Could work, but then I'll have to do some more work on the back-end again, because I thought that people with installed resources would like to use the latest version without copy pasting their documentation stuff into a PUT request. Thus right now they can put their installed resources as is (nothing has to change) and publish them via a chosen URI
