### ISSUE TITLE
Installing a resource

### ISSUE THREAD

**Issue by hannesvdvreken** [iRail/The-DataTank#131]
When putting an installed resource, you're asked to give a location of the classfile.

"location : The location, relative to the custom/packages folder, of your class file that represents an installed resource i.e. mypackage/myinstalledresource.class.php."

When putting the resource, next error message is returned:

"The location /var/www/tdt/custom/packages/Packagename/Resourcename.class.php.class.php"

Imho, the location given should be the entire file name (including relative path).

**Comment by coreation** [comment]
Hannes, I've done basically the same thing + the adjustments for the export functionality in a previous commit. Thanks though for logging it! the documentation about installed and the workflow was inconsistent :).
