### ISSUE TITLE
installed resource deleter

### ISSUE THREAD

**Issue by hannesvdvreken** [iRail/The-DataTank#132]
in branch develop

file /model/resources/delete/InstalledResourceDeleter.class.php

How sure are you not to delete a package that still has some resources left?
(not tested myself)

**Comment by coreation** [comment]
Not sure what your question is, but Deleting is an Admin operation, this means that you have Admin responsibilities as well. Deleting a package will delete all of the resources under it, just as you can perform a "DROP *" in a mysql database.
