### ISSUE TITLE
Split TDTInfo/Resources in 2 seperate resources

### ISSUE THREAD

**Issue by lievenjanssen** [iRail/The-DataTank#16]
Split TDTInfo/Resources in 2 seperate resources:
- TDTInfo/ResourceTree contains the hierarchical package structure without the resource details
- TDTInfo/Resources contains the hierarchical package structure with the resource details

Detailed information in TDTInfo/ResourcesDetail:
- doc
- params
- tags
- columns
- formatters
- ...

**Comment by coreation** [comment]
Split into TDTAdmin/Resources and TDTInfo/Resources
