### ISSUE TITLE
Supported formatters

### ISSUE THREAD

**Issue by lievenjanssen** [iRail/The-DataTank#17]
You need to be able to define on resource level which formatters can to be supported.

For a generic resource you need to be able to predefine formatters but you also need to have the ability to submit the formatters property during the rest call.

e.g. an excel resource will not support the kml formatter by default but when it contains long & lat column names it will be supported

p.s. formatters will have parameters so you can map a column name to long & lat if you want, in this case I won't add it to the directly supported formatters because you still need to manually format.

For installed resource you need to be able to predefine the formatters in code.

**Comment by coreation** [comment]
closed for now.
