### ISSUE TITLE
SPECTQL Group By + Sum, Min, Max, Avg support

### ISSUE THREAD

**Issue by lievenjanssen** [iRail/The-DataTank#22]
Add support for group by with sum, min, max, avg

Necessary for a lot of charting applications.

**Comment by lievenjanssen** [comment]
@coreation can this be closed?

**Comment by coreation** [comment]
I believe so yes, I've recalculated some tests with a calculator on AVG and sum functions and it matches so afai this can be closed.

**Comment by pietercolpaert** [comment]
Please test before closing! Tickets have been closed in the past that introduced a bunch of new small bugs. FlatTurtle is heavily relying on spectql, so this needs to work properly.
