### ISSUE TITLE
Documentation Remote Resource is not available

### ISSUE THREAD

**Issue by lievenjanssen** [iRail/The-DataTank#24]
The documentation for a remote resource is not available.

See http://data.appsforghent.be DL & NMBS package

**Comment by coreation** [comment]
Hmm, I don't know the resource, but is it available ? If i try the link ( with the /municipal) I get no result whatsoever.... maybe the remote resource is down ?

**Comment by lievenjanssen** [comment]
/municipal?

These are the resources I'm talking about:
http://data.appsforghent.be/DL/Stations/
http://data.appsforghent.be/DL/Liveboard/
http://data.appsforghent.be/NMBS/Liveboard/
http://data.appsforghent.be/NMBS/Stations/

When you look at the bottom of the overview page you see that the documentations shows 'No documentation specified'

**Comment by coreation** [comment]
took me exactly one character to fix it !! =D
