### ISSUE TITLE
CSV Strategy: small bugs & issues

### ISSUE THREAD

**Issue by lievenjanssen** [iRail/The-DataTank#38]
1) uri parameter should be renamed to url
2) when columns are ommitted PK param only accepts position of  the column instead of name of the column
3) has_header_row should be default 1 --> not required
4) add default value for delimiter as well?

**Comment by coreation** [comment]
Why should the PK param only accept positions of the column ?

**Comment by lievenjanssen** [comment]
currently it only accepts positions while it should be changed to also accept column names.

I will take care of the necessary changes.

**Comment by coreation** [comment]
All accept the first point of the issue are fixed, the first will have some deeper impact probably.

**Comment by coreation** [comment]
Writing a new issue for the change from uri to url
