### ISSUE TITLE
TDTInfo/Resources - Update

### ISSUE THREAD

**Issue by coreation** [iRail/The-DataTank#48]
The Resources class will also allow updates on definitions by REST specifying a piece of the definiton and passing a replacement.

**Comment by marc-portier** [comment]
don't forget to implement these as a full resource

TDTInfo/Resources/{resourceName} 

should support both GET and PUT, so a UI can be developed that 
- presents the current settings (obtained by GET)
- allows to modify and save (by PUT)

**Comment by coreation** [comment]
What about Creating them by PUT and updating them by POST?

**Comment by marc-portier** [comment]
I was making a statement about GET the resource definition in json or other format (the big missing thing ATM) 
in such a way that you can modify the definition representation and PUT it back again for an update.

Be precise in using the word "update" though.
For me update = any change, of which there are two flavours: overwrite (through PUT) or ammend/partial update (through PATCH)

This view on PU allows to write as to a file: both create and update is there.

POST then is useful for lots of things, but we should be careful in selecting when and how:
- as an alternative to PATCH it can surely be used, since PATCH is new and little used, for lots unclear
- as an alternative to create it can be used too. But typically this is only done if the server assigns the resource-name (by assigning a unique identifier) - In that case the typical response is 201 CREATED together with a Location: header pointing to the new and created resource (which later can be modified through PUT)

Also make sure we all see the difference between this issue and #61

**Comment by coreation** [comment]
There is no difference. I summed up all the issues that resulted from our meeting and I think I have put this issue before that meeting because of what Pieter told me about what you said on Apps For Ghent. What I currently have done is make POST the update mechanism and save PUT solely for the full creation. Is this "wrong" in some way? As I understand POST is used in a correct way as it is now ?

**Comment by marc-portier** [comment]
Here is what things would normally look like in a Resource Oriented Architecture (REST?)

at resource TDTInfo/Resource/{resourceName} where resrouceName is e.g. "my-test/whateverdepth/somedataset"

I would expect to be able to 

GET 

> returning 200 + body holding the resource-definition in some content-negotiated format or at least json (default)
>   { "name":  "my-test/whateverdepth/somedataset", "resource_type": "generic", .... all other params} 

note: the "name" property for convenience, but no hard requirement

> or 404 if that resource doesn't exist yet

PUT + body holding a similar representation (I'm not fond of the request-params alternative, but it seems a viable alternative, and more important: that already works)

> overwriting the resource-definition if it exists, or creating it if it doesn't
>    you might be leniant again on the fact that name property is missing  
>    if it is present: you might 409 conflict if that name doesn't match the resource-name where the put was directed to

DELETE

> to remove the definition and the associated resource

the above methods all need to be idempotent, additionally GET should be safe
hopefully this shows clearly that there is no need (or room) for POST in a pure and classic REST approach

the above is the least you do imho, below is some additional stuff that happens now and then

PATCH (possibly disguised as a POST in case your platform doesn't allow to react upon this new HTTP method)

> to allow modifying the resource-definition through so-called partial-update 

   In this technique you no longer require a change (as with PUT) to hold a full body representation with all fields in there.
   In stead you allow a PATCH + body containing some partial-patch-delta-format listing which parts should be modified/deleted

For datatank resources this doesn't really make sense: the resource definitions are small things: there is little gain expected from partial updates

POST for modifications: doesn't really make sense: nothing PUT can't handle

POST for create: this only makes sense if you want to the server to decide on your resourcename
in this case you POST to TDTInfo/Resources/  (notice: no resource-name)
with body the resource-definition (in json or request params)

response is then 201 CREATED, and a Content-Location header pointing to the resource created.
that would be e.g /server-managed/resource-number-000001

once you have this you would expect a PUT to TDTInfo/Resources//server-managed/resource-number-000001 to work for updates/changes

Oh and buy a copy of http://shop.oreilly.com/product/9780596529260.do :)

**Comment by lievenjanssen** [comment]
Marc,

thanks for the above comment, Jan does this make everything clear to you?

In short forget POST (cause we currently don't let the server decide on the resource name) and use PUT to create and update RESTful resources.

The overview table in the wikipedia article also explains this quite well: http://en.wikipedia.org/wiki/Representational_state_transfer

**Comment by coreation** [comment]
At first sight it's not very easy in code to make a difference between a PUT meant for a re-create or a first time create. PATCH is specifically for partial updates, and that's what we're trying to accomplish in this issue imho. Because updating a resource entirely is already present througha re-PUT of the definition, the partial properties of a definition are the real issue here...?

**Comment by coreation** [comment]
Just as Marc said ( just to advocate PATCH for partial updates ):

Be precise in using the word "update" though.
For me update = any change, of which there are two flavours: overwrite (through PUT) or ammend/partial update (through PATCH)

**Comment by coreation** [comment]
just FYI: PATCH is already included in the list of HTTP Requests in the REST-console of google chrome.

**Comment by marc-portier** [comment]
Thanx to the comment of @coreation in #61 I've (shame on me) learned about the availability of the resource definition already via GET.

however on my instalment
    GET of http://{server}/{subdir}/TDTInfo/Resources/{package}/{resourcename}.json 
will only produce:
    {"gdocs-extra":{"doc":"extra poi from gdocs","requiredparameters":[],"parameters":[]}}

so the parameters are not in there: only empty arrays.

I'm also not really fond of the parameters/required parameters split, but that's just me (I think validation and business rules should come from some schema for each type retrieved from /TDTInfo/Admin/{resource_type}.json )

**Comment by coreation** [comment]
Did you pull from the latest development branch already ? Normally TDTInfo/Resources will provide you with every datamember (even the derived ones) of every resource. The parameters are indeed not instance dependent but "class" dependent, will log this as a new issue.

**Comment by marc-portier** [comment]
now testing on 65ff18487f71f54a38e1585556296c78afd35828

$ curl http://localhost/TheDataTank/TDTInfo/Resources/MyPackage/gdocs-extra.json
{"gdocs-extra":{"doc":"extra data from gdocs","requiredparameters":[],"parameters":[]}}

parameters still empty.

What is the status now on PUT and what represenation should I send through PUT or PATCH?

**Comment by coreation** [comment]
Okay so first of parameters of generic resources will be empty because of their generic nature. There are still however TDT's out there who are possibly proxying resources and expecting an interface in which parameters is given, even if its empty parameters are a part of a resource.

PUT has kept his functionality so:
creating new resources
overriding resources with an entirely new one

PATCH:
partially overriding the definition of the resource.

**Comment by coreation** [comment]
Update dear coders ! As you can derive from the discussion on issue #76. There now is a distinction between public documentation and full descriptions. It's fairly intuitive that descriptions you PUT, sometimes aren't fit for public view. ( see context issue #76 ). Therefore all PUT, PATCH and GET ( GET requests on definitions ) will now go via TDTAdmin/Resources. TDTInfo/Resources has been rolled back to its former form, which just shows you a documentation string on what the resource contains.

**Comment by coreation** [comment]
Didn't take into regard that columns are a part of some resources. To update these some more logic had to be applied, also empty parameters are now deleted as they gave some errors in some resources ( such as XLS ). Will further investigate whether this should be caught in the update/create or if it's the responsibility of the strategy implementor. A use-case i.e. resetting  a PK to "" this is an empty parameter and won't reach the strategy for it will be stripped. This however gave some severe exceptions in the XLS resource if i.e. named_range was passed along with an empty string.

**Comment by marc-portier** [comment]
Could you clarify how the PUT/PATCH now get their data?
- Request params?
- or also body in which format?

Note: when supporting patch you need some mechanism to delete properties (not always the same as setting them to "")

**Comment by coreation** [comment]
Well passing data can be done by your normal request params or a json body. The logic looks into the content-type if it's json, it will accept it, so no support for xml or w/e format just yet.

Same goes for patch.

Not too sure about deleting properties, some aren't meant to be deleted i.e. documentation.

**Comment by coreation** [comment]
Wasn't thinking clear actually DELETING properties in general doesn't make sense.

1) You cannot touch installed / core resources, there it would make sense since you can alter everything, but ofcourse this can only be done manually so DELETE : no

2) You can perform HTTP DELETE's on generic's and remotes. These however form a template of how a certain resource looks like, so DELETE on a property will alwyas result in the empty'ing of an instance of a templated resource (generic or remote). We cannot DELETE a template property because these are untouchable by users. Unless they're fiddling with the code manually ;).

**Comment by marc-portier** [comment]
I assume you mean "DELETING properties in DataTank doesn make sense"?
In "general" DELETE of resource-properties _is_ an issue to cover, but if I read your remark I understand that inside the datatank the resource-definition properties are defined by the built-in schema of the system, so the properties are there, and they could only be cleared, but not deleted, right?

Anyway, what is the conclusion/what do you suggest in the datatank?

Here is how I understand the scenario's to cover and Actions to take

[to resource-definition URI]
- PATCH  with missing property: don't touch it, associated resource gets updated on the other properties of the definition
- PUT  with missing property: it gets cleared, associated resource gets updated to reflect the new definition
- DELETE: resource-definition and associated resource gets deleted

[ro subresource for the property]
- PATCH with no prop value: no change - making it a meaningless null operation (allthough it might 'touch' some lastmod-timestamp)
- PUT with no prop value: clear prop, update associated resource
- DELETE: clear prop, updated associated resource

**Comment by coreation** [comment]
first remark: indeed, correct!

second remark: I think that deleting in TDT for properties is (in a global syntax) not doable since we're working with built-in schema's which are manually built from scratch. So I think for now, deleting properties are not supported.

about the scenario's:

resource-definitions, so if I read this correctly you want to adjust resource definitions by http requests ?
This brings some issues with it, to adjust those parameters, you'll have to delete/adjust every line of code where that parameter is used in the businesslogic...which is pretty much not done? ( again IF I understand you correctly ;) )

Just a question to make sure I'm following your idea : with the PATCH you mean like changing url -> uri ?

for the instances of resources ( adjusting values of instances ) your ideas shouldn't be much of a problem imho.

**Comment by coreation** [comment]
Further discussion is possible on the behaviour, but the core interest of the issue has been implemented, closing the issue!
