### ISSUE TITLE
Remote Resource 

### ISSUE THREAD

**Issue by coreation** [iRail/The-DataTank#49]
Not only the package the should get an alias but also the resourcename itself.

**Comment by coreation** [comment]
Rework of the remote resource:

You can now choose from different alias options:
Say remote resource is data.irail.be/NMBS/Stations, our remote resource can then be:

1) myhost/NMBS/placeswheretrainsstop
parameters: base_url = .... and resource_name = Stations

2) myhost/somepackage/Stations
parameters: base_url = .... and package_name = NMBS

3) myhost/NMBS/Stations
parameters: base_url = ....

**Comment by pietercolpaert** [comment]
no option to specify both a resource_name and a package_name?

**Comment by coreation** [comment]
Oh...forgot that example :D So yes it is possible for both obviously ;)

**Comment by pietercolpaert** [comment]
Nice! Love it :)
