### ISSUE TITLE
Remote resource deletion

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/The-DataTank#7]
When a remote resource is deleted at the originating host, the server will not be informed. When trying to get the documentation at this instance, a code-error will be returned as $doc will not be found.

**Comment by coreation** [comment]
Is this an issue? Or a todo feature? Anyways, will find that out on myself tomorrow.

**Comment by pietercolpaert** [comment]
Issue. It blocks the entire installation when a resource is gone. We just need some checks on whether the remote servers says "package not found" when getting the documentation. It's something we didn't think of so far.

**Comment by coreation** [comment]
Can't we forsee a errorcode for this, so that the remote resource can check the error code to know what went wrong ?

**Comment by pietercolpaert** [comment]
How about the HTTP response code? :D

**Comment by coreation** [comment]
That's what I was going to use ;)
