### ISSUE TITLE
TDTInfo/Documentation vs. TDTInfo/Resources

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/The-DataTank#76]
There is a difference between showing documentation, and showing the meta-data about a resource. I don't want the meta-data about a resource (URI from where it was fetched for instance) to be public, as these URIs may contain credentials or public keys.

Therefore we need another resource:
- TDTInfo/Documentation (read-only) which shows the data that used to be in TDTInfo/Resources: what parameters are needed to get the resource, what required parameters are there, documentation string, and so on. This needs to be cached!
- TDTInfo/Resources (read/write) which shows all meta-data. This resource should be private! Only the administrator can GET/PUT/DELETE/... this resource. It contains the literal data that was PUT-ed.

RFC

**Comment by lievenjanssen** [comment]
Why not create a seperate TDTAdmin package with a TDTAdmin/Resources resource.

For me creating, updating & deleting resources should not be under a package called TDTInfo.

**Comment by pietercolpaert** [comment]
Agreed

**Comment by coreation** [comment]
Sounds reasonable and intuitive !
