### ISSUE TITLE
TDTStats: a new package

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/The-DataTank#8]
TDTStats will be a new core package in The DataTank. It will replace the TDTInfo/Queries.

TDTStats will have more resources like:
- /UserAgents
- /LastWeek
- /Today
- /Overall
- /Errors
- /Languages
- ...

**Comment by qkaiser** [comment]
Great ! Someone is working on a visualisation tool (google analytics-like) ? 
A relevant data could be user's country (if you're providing belgian laws and every request come from canada, there is something wrong with your api for example :D ).

**Comment by pietercolpaert** [comment]
Not yet, as the package has not been made yet. But I figure someone will do that eventually ;) I'll keep you posted!

**Comment by coreation** [comment]
Can I close this issue ? The rework on TDTStats has been done some time ago now... ?

**Comment by pietercolpaert** [comment]
I thnk so, yes :)
