### ISSUE TITLE
deal with empty and double PK in data-source

### ISSUE THREAD

**Issue by marc-portier** [iRail/The-DataTank#83]
Have been testing out with the PK property in generic/CSV resources.

Tests performed:
- leave PK field empty
- use same value "1" twice in PK field (for different rows)

Findings:
- no error-logging or warnings
- no failure, but decent result, however:
- for double keys: the first row with the value is kept, further duplicates are ignored 
- missing PK values are considered as having the valid value "" empty, and thus the first such row is kept in the result

What I would prefer:
- extensive error/warning logging: trace linenumbers that have missing or duplicate PK values
- keep returning a decent result though, no need to fail 
- keep retaining the first value and ignore duplicates
- but also ignore empty PK rows

**Comment by coreation** [comment]
Where would you prefer this warning/error ? Just a log in the back-end, or must there be some kind of feed-back towards the user when these ( empty pk, doubles) occur ?

**Comment by coreation** [comment]
As far as I can see marc you also have 2 similarities in findings and preferences, namely what to do when you have duplicate PK's ?(!)

**Comment by marc-portier** [comment]
sorry for not being clear:
- log at back-end is ok
- current keep-first strategy in the result for duplicate keys is ok, (that is why current finding == expectation :) )
- however the ignored second occurance should be logged
- empty PK should be ignored always, and logged similarly

**Comment by coreation** [comment]
Roger that !

**Comment by coreation** [comment]
Think I'm going to introduce a Logs table to log non-error (or non-severe-error) related stuff. Can't really figure out why we didn't need this in the past.....
